services:
  api:
    image: vegan-restaurants/api
    ports:
      - "3000:3000"
    build: api
    depends_on:
      - db

  website:
    image: vegan-restaurants/website
    ports:
      - "8080:8080"
    build: website
    depends_on:
      - api

  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: vegan_restaurants
